### ISSUE TITLE
Mind control arc

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#167]
Looks like this in RA2:
https://www.youtube.com/watch?v=n4pRltGxveg

**Comment by forcecore** [comment]
https://github.com/forcecore/OpenRA/commit/3953ccf8858eae1069871987bb49f9ed0ce7a46d
https://github.com/forcecore/OpenRA/commit/f76a7e0c17cc000cd0a86b21ba484cb5a6bc720a

**Comment by GraionDilach** [comment]
A suggestion on a quick glampse: Remove the selfdamaging aspects from the logic and instead set it to be a condition granter (controller grants a condition for each linked victim, victim gains a condition for being controlled). I suggest this because Mastermind had selfdamaging levels and not just a single on-off one.

**Comment by forcecore** [comment]
Sounds good

**Comment by forcecore** [comment]
But it seems condition level can't be queried?

**Comment by forcecore** [comment]
CLosing and making separate ticket
