### ISSUE TITLE
Kirov performance issue?

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#77]
I have a message at ModDB that if many Kirov, game gets slow.
10 Kirovs = 50 Migs, lets compare with 50 migs to find out if it is Kirov or the Engine.

**Comment by GraionDilach** [comment]
If the Kirov is a voxel, it's possible due to voxels massively strain the GPU. See https://github.com/OpenRA/OpenRA/issues/4539 and the discussion in https://github.com/OpenRA/OpenRA/pull/11791 for starters.

You can also work around the issue by creating a testmap with a dummy terrain (say, purely pink), place 32 Kirovs there then SHPify a screenshot. Either that, either downsize the Kirov by converting it to TXT with Mixer, running a tool like https://gist.github.com/GraionDilach/fee66c343ec0242b1d285e2f0b86dd90 on it with a modifier of say 0.5, convert the result back to VXL with Mixer, then fixing normals and scale in the header via VXLSE.

**Comment by MustaphaTR** [comment]
Not really a Kirov, but Nooze made a blimp in the past. It lacks of datils like face tho. It should be in my Tower Defence maps on Resource Center if you wanna use it.

But i would prefer an SHP Kirov with the face.

**Comment by forcecore** [comment]
Fixed in 8dfdcde9b416d260ab400f1802d479465ca07380
Used OS voxel viewer to generate all the frames.

**Comment by GraionDilach** [comment]
Ouch, that's really a bad idea. Okay, ping me over Discord on the weekend, I'll do an accurate conversion.
